server:
  port: 4005
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# sleuth配置
spring:
#  zipkin:
#    rabbitmq:
#      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

  datasource:

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 000000

    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initialSize: 2
    minIdle: 1
    maxActive: 1000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.github.pig.admin.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
fdfs:
  file-host: http://127.0.0.1:22121/
  tracker-list:
    - 127.0.0.1:22122

